2024-07-09 16:31:12.462 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 16:31:12.759 +03:00 [FTL] Uygulama başlatılırken bir hata oluştu.
2024-07-09 16:33:11.623 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 16:33:12.041 +03:00 [FTL] Uygulama başlatılırken bir hata oluştu.
2024-07-09 16:35:48.955 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 16:36:39.766 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 16:36:39.788 +03:00 [FTL] Uygulama başlatılırken bir hata oluştu.
2024-07-09 16:37:31.275 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 16:37:31.297 +03:00 [FTL] Uygulama başlatılırken bir hata oluştu.
2024-07-09 16:45:10.631 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 16:48:25.620 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 16:48:25.643 +03:00 [FTL] Uygulama başlatılırken bir hata oluştu.
2024-07-09 16:50:56.259 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 16:58:53.333 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 16:59:20.790 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 16:59:20.814 +03:00 [FTL] Uygulama başlatılırken bir hata oluştu.
2024-07-09 17:00:38.995 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:00:39.019 +03:00 [FTL] Uygulama başlatılırken bir hata oluştu.
2024-07-09 17:02:15.219 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:03:19.892 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:03:34.427 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:03:34.447 +03:00 [FTL] Uygulama başlatılırken bir hata oluştu.
2024-07-09 17:04:05.010 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:04:05.036 +03:00 [FTL] Uygulama başlatılırken bir hata oluştu.
2024-07-09 17:05:22.776 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:05:52.378 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:06:03.099 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:06:35.874 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:07:41.632 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:08:13.238 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:08:31.229 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:10:53.579 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:11:28.898 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:11:59.674 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:14:00.751 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:14:28.149 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:18:27.160 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:20:35.117 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:25:56.550 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:27:28.712 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at TodoListApp.Controllers.NoteController.AddNote(NoteDTO dto) in C:\Users\omen\source\repos\TodoListApp\TodoListApp\Controllers\NoteController.cs:line 28
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-07-09 17:29:29.611 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:35:09.199 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:41:50.260 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:42:02.322 +03:00 [ERR] UserId claim is missing.
2024-07-09 17:42:24.578 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:42:37.441 +03:00 [ERR] UserId claim is missing.
2024-07-09 17:46:45.970 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:46:59.859 +03:00 [ERR] UserId claim is missing.
2024-07-09 17:49:23.404 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:49:36.726 +03:00 [ERR] UserId claim is missing.
2024-07-09 17:54:06.647 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:54:36.654 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action<AuthenticationOptions> configureOptions).
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.<>c__DisplayClass0_0.<<HandleAsync>g__Handle|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-07-09 17:56:12.557 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:56:28.991 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authentication handlers are registered. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-07-09 17:57:46.156 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 17:57:58.990 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authentication handlers are registered. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-07-09 17:59:44.640 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 18:00:03.956 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authentication handlers are registered. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-07-09 18:00:52.634 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 18:01:08.137 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authentication handlers are registered. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-07-09 18:01:46.829 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 18:02:03.796 +03:00 [ERR] UserId claim is missing.
2024-07-09 18:05:57.385 +03:00 [ERR] UserId claim is missing.
2024-07-09 18:10:19.799 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 18:10:30.823 +03:00 [INF] AddNote method called.
2024-07-09 18:10:31.622 +03:00 [ERR] An exception occurred in the database while saving changes for context type 'TodoListApp.Data.ApplicationDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Notes_Users". The conflict occurred in database "TodoListDb", table "dbo.Users", column 'Id'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.Read()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Read()
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSet(Int32 startCommandIndex, RelationalDataReader reader)
ClientConnectionId:27c6e146-1c09-481c-8252-3b962883c3f9
Error Number:547,State:0,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSet(Int32 startCommandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__112_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Notes_Users". The conflict occurred in database "TodoListDb", table "dbo.Users", column 'Id'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.Read()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Read()
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSet(Int32 startCommandIndex, RelationalDataReader reader)
ClientConnectionId:27c6e146-1c09-481c-8252-3b962883c3f9
Error Number:547,State:0,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSet(Int32 startCommandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__112_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
2024-07-09 18:10:37.414 +03:00 [INF] Uygulama başlatılıyor.
2024-07-09 18:10:53.698 +03:00 [INF] AddNote method called.
2024-07-09 18:10:56.866 +03:00 [INF] Note successfully added.
